obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.175, 0.175], [0.175, -0.175], [-0.175, -0.175], [-0.175, 0.175]]
#footprint_inflation: 0.01
<<<<<<< HEAD
robot_radius: 0.1086755
=======
robot_radius: 0.086755
>>>>>>> 1b7c90c1682eada150db18a82c7fd4e120106e32
inflation_radius: 0.55
#max_obstacle_height: 0.6
#min_obstacle_height: 0.0
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: kinect_link,data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
