local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
<<<<<<< HEAD
  width: 10.0
  height: 10.0
=======
  width: 6.0
  height: 6.0
>>>>>>> 1b7c90c1682eada150db18a82c7fd4e120106e32
  resolution: 0.05